name: Node CI/CD

on: [push, pull_request]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npm publish
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
